BRANDS = [
    # Автомобили
    "Mercedes-Benz", "BMW", "Audi", "Toyota", "Honda", "Ford", "Volkswagen", "Porsche", "Ferrari", "Tesla",
    "Lamborghini", "Bentley", "Rolls-Royce", "Maserati", "Jaguar", "Land-Rover", "Volvo", "Lexus", 
    "Chevrolet", "Cadillac", "Chrysler", "Dodge", "Jeep", "Hyundai", "Kia", "Mazda", "Nissan", "Infiniti",
    "Subaru", "Mitsubishi", "Peugeot", "Renault", "Citroen", "Fiat", "Alfa-Romeo", "Skoda", "Seat",
    "Mini", "Smart", "Opel", "Acura", "Genesis", "Bugatti", "McLaren", "Aston-Martin", "Lotus",

    # Технологии и электроника
    "Apple", "Samsung", "Microsoft", "Google", "Intel", "AMD", "Nvidia", "Lenovo", "Dell", "HP",
    "Asus", "Acer", "LG", "Sony", "Panasonic", "Philips", "Huawei", "Xiaomi", "OnePlus", "Vivo",
    "Oppo", "Realme", "Nokia", "Motorola", "BlackBerry", "Toshiba", "Canon", "Nikon", "GoPro", "DJI",
    "Bose", "Beats", "JBL", "Sennheiser", "Logitech", "Western-Digital", "Seagate", "Kingston",

    # Напитки
    "Coca-Cola", "Pepsi", "Fanta", "Sprite", "Red-Bull", "Monster", "Dr-Pepper", "Mountain-Dew",
    "Schweppes", "7Up", "Mirinda", "Gatorade", "Powerade", "Lipton", "Nestea", "Arizona",
    "Heineken", "Carlsberg", "Budweiser", "Corona", "Stella-Artois", "Guinness", "Jack-Daniels",
    "Absolut", "Smirnoff", "Bacardi", "Hennessy", "Moet-Chandon", "Dom-Perignon", "Evian",
    "Perrier", "San-Pellegrino", "Voss", "Fiji-Water",

    # Одежда и обувь
    "Nike", "Adidas", "Puma", "Reebok", "Under-Armour", "New-Balance", "Asics", "Converse",
    "Vans", "Timberland", "Dr-Martens", "Gucci", "Louis-Vuitton", "Prada", "Hermes", "Chanel",
    "Dior", "Balenciaga", "Versace", "Fendi", "Burberry", "Ralph-Lauren", "Tommy-Hilfiger",
    "Calvin-Klein", "Hugo-Boss", "Lacoste", "The-North-Face", "Columbia", "Patagonia", "Zara",
    "H&M", "Uniqlo", "Gap", "Levi's", "Diesel", "Supreme", "Off-White", "Stone-Island",

    # Авиакомпании
    "American-Airlines", "Delta", "United-Airlines", "Lufthansa", "British-Airways", "Air-France",
    "KLM", "Emirates", "Qatar-Airways", "Etihad", "Singapore-Airlines", "Turkish-Airlines",
    "Air-Canada", "Cathay-Pacific", "Virgin-Atlantic", "EasyJet", "Ryanair", "Southwest",
    "JetBlue", "Alaska-Airlines", "Aeroflot", "Air-China", "Japan-Airlines", "Korean-Air",

    # Сотовые операторы
    "Verizon", "AT&T", "T-Mobile", "Vodafone", "Orange", "Deutsche-Telekom", "Telefonica",
    "China-Mobile", "NTT-Docomo", "SoftBank", "Sprint", "O2", "Three", "EE", "MTS", "Beeline",
    "Megafon", "Tele2", "Rogers", "Bell",

    # Фастфуд и рестораны
    "McDonald's", "Burger-King", "KFC", "Subway", "Pizza-Hut", "Domino's", "Wendy's",
    "Taco-Bell", "Starbucks", "Dunkin-Donuts", "Baskin-Robbins", "Papa-John's",
    "Chipotle", "Five-Guys", "Shake-Shack", "Popeyes", "Chick-fil-A", "Arby's",

    # Продукты питания
    "Nestle", "Unilever", "P&G", "Kraft-Heinz", "Danone", "Kellogg's", "General-Mills",
    "Mars", "Ferrero", "Mondelez", "Campbell's", "Hershey's", "Oreo", "Lay's", "Doritos",
    "Pringles", "Nutella", "Snickers", "M&M's", "Cadbury",

    # Розничная торговля
    "Amazon", "Walmart", "Target", "Costco", "Ikea", "Home-Depot", "Best-Buy", "Aldi",
    "Lidl", "Carrefour", "Tesco", "Sainsbury's", "7-Eleven", "Whole-Foods", "Kroger",

    # Банки и финансы
    "Visa", "Mastercard", "American-Express", "PayPal", "Goldman-Sachs", "JP-Morgan",
    "HSBC", "Citibank", "Bank-of-America", "Wells-Fargo", "Deutsche-Bank", "Barclays",

    # Спортивные лиги и команды
    "NBA", "NFL", "MLB", "NHL", "FIFA", "UEFA", "Real-Madrid", "Barcelona", "Manchester-United",
    "Liverpool", "Chelsea", "Bayern-Munich", "Juventus", "PSG",

    # Развлечения и медиа
    "Netflix", "Disney", "Warner-Bros", "Sony-Pictures", "Universal", "Paramount",
    "HBO", "ESPN", "BBC", "CNN", "Fox", "Spotify", "YouTube", "TikTok", "Instagram",
    "Facebook", "Twitter", "Snapchat", "LinkedIn", "Pinterest",

    # Игровые компании
    "Nintendo", "PlayStation", "Xbox", "Electronic-Arts", "Ubisoft", "Activision",
    "Blizzard", "Rockstar-Games", "Epic-Games", "Valve", "Sega", "Capcom",

    # Косметика и красота
    "L'Oreal", "Estee-Lauder", "MAC", "Maybelline", "Nivea", "Dove", "Garnier",
    "Clinique", "Lancome", "Shiseido", "Avon", "Revlon", "Urban-Decay", "NYX",
    
    # Отели
    "Hilton", "Marriott", "Hyatt", "Sheraton", "Westin", "Ritz-Carlton",
    "Four-Seasons", "InterContinental", "Holiday-Inn", "Radisson", "Novotel",
"row-cell-value 2",
"JPMorganChase",
"Berkshire Hathaway",
"Saudi Arabian Oil Company (Saudi Aramco)",
"ICBC",
"Bank of America",
"Amazon",
"China Construction Bank",
"Microsoft",
"Agricultural Bank of China",
"Alphabet",
"Toyota Motor",
"Apple",
"Bank of China",
"ExxonMobil",
"HSBC Holdings",
"Wells Fargo",
"Shell Plc",
"PetroChina",
"UnitedHealth Group",
"Walmart",
"Samsung Electronics",
"Chevron",
"Goldman Sachs Group",
"Meta Platforms",
"TotalEnergies",
"Morgan Stanley",
"RBC",
"Citigroup",
"Ping An Insurance Group",
"China Mobile",
"Allianz",
"BNP Paribas",
"Verizon Communications",
"China Merchants Bank",
"UBS",
"Santander",
"AT&T",
"Tencent Holdings",
"Mitsubishi UFJ Financial",
"Comcast",
"Alibaba Group",
"Sinopec",
"Volkswagen Group",
"TD Bank Group",
"Johnson & Johnson",
"Taiwan Semiconductor",
"BP",
"LVMH Moët Hennessy Louis Vuitton",
"Reliance Industries",
"Nestlé",
"JPMorganChase",
"Berkshire Hathaway",
"Saudi Arabian Oil Company (Saudi Aramco)",
"ICBC",
"Bank of America",
"Amazon",
"China Construction Bank",
"Microsoft",
"Agricultural Bank of China",
"Alphabet",
"Toyota Motor",
"Apple",
"Bank of China",
"ExxonMobil",
"HSBC Holdings",
"Wells Fargo",
"Shell Plc",
"PetroChina",
"UnitedHealth Group",
"Walmart",
"Samsung Electronics",
"Chevron",
"Goldman Sachs Group",
"Meta Platforms",
"TotalEnergies",
"Morgan Stanley",
"RBC",
"Citigroup",
"Ping An Insurance Group",
"China Mobile",
"Allianz",
"BNP Paribas",
"Verizon Communications",
"China Merchants Bank",
"UBS",
"Santander",
"AT&T",
"Tencent Holdings",
"Mitsubishi UFJ Financial",
"Comcast",
"Alibaba Group",
"Sinopec",
"Volkswagen Group",
"TD Bank Group",
"Johnson & Johnson",
"Taiwan Semiconductor",
"BP",
"LVMH Moët Hennessy Louis Vuitton",
"Reliance Industries",
"Nestlé",
"AXA Group",
"Mercedes-Benz Group",
"American Express",
"Petrobras",
"State Bank of India",
"Bank of Communications",
"Postal Savings Bank Of China (PSBC)",
"Tesla",
"Procter & Gamble",
"Stellantis",
"BMW Group",
"Deutsche Telekom",
"Sumitomo Mitsui Financial",
"CVS Health",
"HDFC Bank",
"BBVA-Banco Bilbao Vizcaya",
"Sony",
"Siemens",
"Commonwealth Bank",
"Life Insurance Corp. of India",
"General Motors",
"Nippon Telegraph & Tel",
"Credit Agricole",
"Broadcom",
"PepsiCo",
"The Home Depot",
"Oracle",
"Mitsubishi",
"Roche Holding",
"Equinor",
"Elevance Health",
"CNOOC",
"Industrial Bank",
"Intesa Sanpaolo Assicura",
"IBM",
"Chubb",
"Itaú Unibanco Holding",
"Anheuser-Busch InBev",
"AbbVie",
"Cisco Systems",
"Honda Motor",
"Bank of Nova Scotia",
"Hyundai Motor",
"Enel",
"Cigna",
"Costco Wholesale",
"Munich Re",
"Zurich Insurance Group",
"Novartis",
"Coca-Cola",
"GE Aerospace",
"Caterpillar",
"John Deere",
"Bank of Montreal",
"Mizuho Financial",
"AIRBUS",
"Intel",
"Mitsui",
"ConocoPhillips",
"China State Construction Engineering",
"NVIDIA",
"Rio Tinto",
"CITIC",
"RTX",
"Glencore International",
"BHP Group",
"China Life Insurance",
"US Bancorp",
"Hon Hai Precision",
"Iberdrola",
"AstraZeneca",
"Sanofi",
"Unilever",
"Ford Motor",
"Capital One",
"NAB - National Australia Bank",
"Apollo Global Management",
"Visa",
"UniCredit",
"Contemporary Amperex Technology",
"American International Group",
"ANZ Group Holdings",
"VINCI",
"China Citic Bank",
"Thermo Fisher Scientific",
"Charles Schwab",
"Progressive",
"DBS",
"Marathon Petroleum",
"PNC Financial Services",
"Generali Group",
"ICICI Bank",
"Itochu",
"Westpac Banking Group",
"United Parcel Service",
"Deutsche Bank",
"Canadian Imperial Bank",
"China Shenhua Energy",
"Tokio Marine Holdings",
"NextEra Energy",
"Eni",
"BYD",
"ING Group",
"Lloyds Banking Group",
"Walt Disney",
"Phillips 66",
"MetLife",
"Salesforce",
"Shanghai Pudong Development",
"Banco do Brasil",
"AIA Group",
"Merck & Co.",
"Abbott Laboratories",
"China Telecom",
"Dell Technologies",
"Barclays",
"Linde",
"FedEx",
"Hitachi",
"Accenture",
"Lockheed Martin",
"L'Oréal",
"Nordea Bank",
"Eli Lilly",
"KKR",
"Philip Morris International",
"NatWest Group",
"Valero Energy",
"Enbridge",
"JD.com",
"Bank of New York Mellon",
"Vale",
"GSK",
"Prudential Financial",
"Lowe's",
"Charter Communications",
"Honeywell International",
"McKesson",
"Duke Energy",
"Qualcomm",
"HCA Healthcare",
"Medtronic",
"Amgen",
"ENGIE",
"Southern Company",
"CaixaBank",
"Manulife",
"Danaher",
"Mondelez International",
"Schneider Electric",
"Target",
"Deutsche Post",
"KDDI",
"National Grid",
"Midea Group",
"Novo Nordisk",
"Oil & Natural Gas",
"América Móvil",
"BlackRock",
"PDD Holdings",
"PICC",
"Netflix",
"Brookfield Corporation",
"Qatar National Bank",
"International Holding Company",
"Travelers",
"Volvo Group",
"Union Pacific",
"Oversea-Chinese Banking",
"Swiss Re",
"China Pacific Insurance",
"McDonald's",
"Banco Bradesco",
"Centene",
"PayPal",
"Japan Post Holdings",
"Standard Chartered",
"China Everbright Bank",
"Suncor Energy",
"SAP",
"Mastercard",
"The Saudi National Bank",
"China Resources Land",
"Delta Air Lines",
"KIA",
"ASML Holding",
"General Dynamics",
"Daimler Truck Holding",
"Nike",
"United Overseas Bank",
"KBC Group",
"First Abu Dhabi Bank",
"PTT",
"Canadian Natural Resources",
"Aflac",
"Dai-ichi Life Insurance",
"Occidental Petroleum",
"China Minsheng Bank",
"Société Générale",
"KB Financial Group",
"Inditex",
"Al Rajhi Bank",
"MS&AD Insurance",
"Air Liquide",
"Fiserv",
"China Railway Group",
"Orange",
"Safran",
"Indian Oil",
"Emirates NBD",
"EssilorLuxottica",
"Cencora",
"SLB",
"Saint-Gobain",
"Danske Bank",
"Macquarie Group",
"Zijin Mining Group",
"TJX Cos",
"Banorte",
"Kweichow Moutai",
"Fubon Financial",
"SAIC Motor",
"Automatic Data Processing",
"Kraft Heinz Company",
"Holcim",
"ABB",
"EOG Resources",
"Applied Materials",
"E.ON",
"Denso",
"DNB Bank",
"Archer Daniels Midland",
"Marsh McLennan",
"Tata Motors",
"Sumitomo",
"Paccar",
"Fairfax Financial",
"PG&E",
"SEB AB",
"Allstate",
"Kroger",
"Erste Group Bank",
"Axis Bank",
"Humana",
"Ameriprise Financial",
"Marubeni",
"Bank Of Jiangsu",
"CRH",
"China Unicom",
"Sun Life Financial",
"American Electric",
"Banco Btg Pactual",
"Northrop Grumman",
"Shinhan Financial Group",
"Couche Tard",
"Xiaomi",
"CK Hutchison",
"Bank Rakyat Indonesia (BRI)",
"Koç Holding",
"Merck KGaA, Darmstadt, Germany and its affiliates",
"Commerzbank",
"Meituan",
"Seven & I Holdings",
"Diageo",
"Eaton",
"Cathay Financial",
"Ecopetrol",
"Talanx",
"Starbucks",
"Altria Group",
"Exelon",
"D.R. Horton",
"National Bank of Canada",
"Discover Financial Services",
"Nippon Steel",
"Royal Ahold Delhaize N.V.",
"Lennar",
"Stryker",
"Richemont",
"Huaxia Bank",
"Power Corp of Canada",
"Repsol",
"Bank of Ningbo",
"Gree Electric Appliances",
"Cenovus Energy",
"Texas Instruments",
"RWE Group",
"Constellation Energy",
"Møller-Maersk",
"Renault",
"Nissan Motor",
"Panasonic",
"Advanced Micro Devices",
"Hartford Financial Services",
"Adobe",
"Sompo",
"Uber",
"Bank of Beijing",
"Vodafone",
"China Railway Construction",
"Poly Developments & Holdings Group",
"Japan Tobacco",
"Freeport-McMoRan",
"Fannie Mae",
"Nucor",
"Booking Holdings",
"Canadian National Railway",
"Corebridge Financial",
"Tesco",
"United Airlines Holdings",
"BAE Systems",
"HP",
"S&P Global",
"Cosco Shipping",
"Freddie Mac",
"Sempra",
"China Communications Construction",
"Kering",
"State Street",
"Saudi Telecom",
"China Yangtze Power",
"NTPC",
"Bank Mandiri",
"Aviva",
"Swedbank",
"Baidu",
"First Citizens Bank (NC)",
"Svenska Handelsbanken",
"Orix",
"Dow",
"IntercontinentalExchange",
"Power Construction Corporation of China",
"Toyota Tsusho",
"Takeda Pharmaceutical",
"Poste Italiane",
"Mitsubishi Electric",
"Citic Securities",
"Haier Smart Home",
"Kinder Morgan",
"Toyota Industries",
"Rolls-Royce Holdings",
"Fortescue Metals Group",
"Waste Management",
"Cheniere Energy",
"TAQA",
"CSX",
"Johnson Controls International",
"Larsen & Toubro",
"Femsa",
"Dominion Energy",
"LyondellBasell Industries",
"Shin-Etsu Chemical",
"Investor AB",
"M&T Bank",
"ORLEN Spolka Akcyjna",
"Arch Capital Group",
"Synchrony Financial",
"Fifth Third Bank",
"Becton Dickinson",
"ENEOS Holdings",
"Hana Financial Group",
"Posco",
"Tata Consultancy Services",
"Schweizerische Nationalbank",
"Prologis",
"Wanhua Chemical Group",
"Oneok",
"Analog Devices",
"Parker-Hannifin",
"Baoshan Iron & Steel",
"ArcelorMittal",
"Nomura",
"Bank Of Shanghai",
"American Tower",
"Hewlett Packard Enterprise",
"Marriott International",
"Regeneron Pharmaceuticals",
"Intuit",
"Sysco",
"Daikin Industries",
"Veolia Environnement",
"Bridgestone",
"Cummins",
"Michelin Group",
"Komatsu",
"Pfizer",
"CSL",
"Keurig Dr Pepper",
"Canadian Pacific Kansas City",
"Bank of Baroda",
"CTBC Financial Holding",
"Kotak Mahindra Bank",
"TC Energy",
"Carrier Global",
"Aon",
"Hermès International",
"Mitsubishi Heavy Industries",
"Infineon Technologies",
"Heineken",
"Boeing",
"Grupo Mexico",
"London Stock Exchange",
"Sherwin-Williams",
"Dollar General",
"Baker Hughes Company",
"CRRC",
"Bank Central Asia",
"Boston Scientific",
"Naturgy Energy Group",
"Saudi Electricity",
"Softbank",
"Wilmar International",
"China Vanke",
"Maybank",
"Hyundai Mobis",
"General Mills",
"Canon",
"Consolidated Edison",
"Kansai Electric Power",
"Danone",
"BT Group",
"Bharti Airtel",
"Etisalat",
"OMV Group",
"Fast Retailing",
"Carrefour",
"NetEase",
"Compass Group",
"Principal Financial Group",
"BCE",
"Prudential",
"Suzuki Motor",
"FirstRand",
"Sun Hung Kai Properties",
"Recruit Holdings",
"Williams",
"Xcel Energy",
"Coal India",
"Kuwait Finance House",
"Raymond James Financial",
"Reckitt Benckiser Group",
"China Coal Energy",
"Samsung C&T",
"Longfor Group Holdings",
"Blackstone",
"Daiwa House Industry",
"Shaanxi Coal Industry",
"China Merchants Shekou Industrial Zone Holdings",
"Mitsui Fudosan",
"Henkel",
"Imperial Brands",
"Truist Financial",
"L3Harris Technologies",
"Air Products & Chemicals",
"Woodside Energy Group",
"Capgemini",
"NN Group",
"Legal & General Group",
"Republic Services",
"Halliburton",
"Bouygues",
"Pernod Ricard",
"Bristol Myers Squibb",
"Coca-Cola Europacific Partners",
"Yankuang Energy Group",
"Markel",
"Huntington Bank",
"Tokyo Electric Power",
"CME Group",
"STMicroelectronics",
"Swiss Life Holding",
"Edison International",
"GE HealthCare Technologies",
"Thales",
"Canara Bank",
"Isbank",
"Nutrien",
"British American Tobacco",
"East Japan Railway",
"Central Japan Railway",
"Bank of Nanjing",
"TE Connectivity",
"Power Finance",
"Royal Caribbean Group",
"HeidelbergCement",
"AirBnB",
"Bharat Petroleum",
"LG Chem",
"Turkish Airlines",
"Wuliangye Yibin",
"Subaru Corporation",
"Weichai Power",
"Luxshare Precision Industry",
"Atlas Copco",
"United Rentals",
"CNH Industrial",
"Loews",
"Entergy",
"Quanta Computer",
"BASF",
"NXP Semiconductors",
"Lam Research",
"Vertex Pharmaceuticals",
"Citizens Financial Group",
"Xiamen C&D",
"S.F. Holding",
"Norfolk Southern",
"Deutsche Boerse",
"Intact Financial",
"Fujifilm Holdings",
"Everest Re Group",
"OTP Bank",
"Trane Technologies",
"Inpex",
"Wesfarmers",
"Colgate-Palmolive",
"Samsung Life Insurance",
"Haleon",
"Infosys",
"Devon Energy",
"Punjab National Bank",
"Publicis Groupe",
"MediaTek",
"SK Hynix",
"Gilead Sciences",
"Union Bank of India",
"Abu Dhabi Commercial Bank",
"Gallagher",
"International Airlines",
"Fujitsu",
"Public Service Enterprise Group",
"Aptiv",
"Bayer",
"China Zheshang Bank",
"George Weston",
"Cardinal Health",
"Kubota",
"Regions Financial",
"Bunge",
"Equitable Holdings",
"China National Nuclear Power",
"Bajaj Finserv",
"Mahindra & Mahindra",
"Nintendo",
"Kenvue",
"National Bank of Kuwait",
"Barrick Gold",
"Coinbase",
"Ecolab",
"AutoZone",
"Illinois Tool Works",
"DSV",
"Standard Bank Group",
"Associated British Foods",
"Lenovo Group",
"Northern Trust",
"Reinsurance Group of America",
"Nokia",
"PKO Bank Polski",
"Ferguson",
"Grupa PZU",
"IQVIA",
"Woori Financial Group",
"Edp-energias De Portugal",
"Hess",
"Naspers",
"Swire Pacific",
"Kimberly-Clark",
"China Tower Corp.",
"SingTel",
"Chubu Electric Power",
"CMOC Group",
"Hengli Petrochemical",
"QBE Insurance Group",
"Riyad Bank",
"Sinopharm Group",
"Telefónica",
"Telstra",
"Cognizant",
"3M",
"Industrial Bank of Korea",
"NRG Energy",
"CBRE Group",
"Tokyo Electron",
"Metallurgical Corp of China",
"Bank Of Hangzhou",
"CEZ Group",
"Micron Technology",
"China Energy Engineering",
"AerCap Holdings",
"CGN Power",
"Swisscom",
"Diamondback Energy",
"New China Life Insurance",
"JSW Steel",
"RELX",
"Raiffeisen Bank International",
"Asahi Group Holdings",
"Bank Leumi",
"DTE Energy",
"Centrica",
"Nu Holdings",
"Albertsons",
"Ally Financial",
"Anglo American",
"GD Power Development",
"FirstEnergy",
"PPG",
"Bank Hapoalim",
"Tenet Healthcare",
"Ross Stores",
"Global Payments",
"MercadoLibre",
"Anhui Conch Cement",
"Deutsche Lufthansa",
"Akbank",
"Inner Mongolia Yili",
"Teck Resources",
"Amphenol",
"Magna International",
"Great Wall Motor",
"Jardine Matheson",
"Warner Bros. Discovery",
"CIMB Group Holdings",
"O'Reilly Automotive",
"Asr Nederland",
"Daiichi Sankyo",
"Tenaris",
"Constellation Brands",
"GE Vernova",
"Continental",
"Samsung SDI",
"Huaneng Power International",
"Hindalco Industries",
"Banco de Sabadell",
"Bank of Ireland",
"Aeon",
"Sumitomo Mitsui Trust",
"Walgreens Boots Alliance",
"NEC",
"Idemitsu Kosan",
"Vistra Energy",
"W. R. Berkley",
"Corteva",
"Lincoln National",
"WEC Energy Group",
"Singapore Airlines",
"Hikvision",
"Mitsubishi Estate",
"Coupang",
"Li Auto",
"ServiceNow",
"Samsung Fire & Marine",
"China Hongqiao Group",
"Cincinnati Financial",
"KeyCorp",
"Block",
"PulteGroup",
"Saudi British Bank",
"JFE Holdings",
"Korea Electric Power",
"Banco BPM",
"Omnicom Group",
"EnBW Energie Baden-Wurttemberg",
"ACS Actividades de Construccion y Servicios",
"WW Grainger",
"BOE Technology Group",
"Equinix",
"Nippon Yusen",
"Emaar Properties",
"Kuehne & Nagel International",
"KLA",
"Porsche Automobil Holding",
"Crown Castle International",
"Eiffage",
"Sekisui House",
"Las Vegas Sands",
"Alcon",
"VICI Properties",
"Simon Property Group",
"Genuine Parts",
"Renesas Electronics",
"Verbund",
"China Resources Power",
"Fidelity National Financial",
"eBay",
"Volvo Car",
"LG Electronics",
"Emerson Electric",
"Palo Alto Networks",
"Assa Abloy",
"Keyence",
"Sumitomo Electric",
"Siemens Energy",
"Steel Dynamics",
"Grasim Industries",
"Aluminum Corp of China",
"Ashtead Group",
"Sika",
"Huatai Securities",
"AIB Group",
"Meritz Financial Group",
"Hong Kong Exchanges",
"Fortis (Canada)",
"Targa Resources",
"Ryanair Holdings",
"3i Group",
"Roper Technologies",
"VakifBank",
"Chongqing Changan Auto",
"MGM Resorts",
"RenaissanceRe Holdings",
"Huishang Bank",
"HCLTech",
"Molina Healthcare",
"Neste",
"Thomson Reuters",
"Aegon",
"Bancolombia",
"ASE Technology Holding",
"Rongsheng Petrochemical",
"Resona Holdings",
"Jabil Circuit",
"Grupo Inbursa",
"Biogen",
"Daqin Railway",
"The Estée Lauder Companies",
"Suncorp Group",
"SSE",
"Murata Manufacturing",
"Celanese",
"TransDigm Group",
"Beijing-Shanghai High-Speed Railway",
"Newmont",
"Tyson Foods",
"Ageas",
"Nidec",
"Zoetis",
"CK Asset Holdings",
"H&M - Hennes & Mauritz",
"Public Bank",
"TELUS",
"Sampo",
"Best Buy",
"Galp Energia",
"Shanghai Rural Commercial Bank",
"WTW",
"Intuitive Surgical",
"Otsuka Holding",
"Unum Group",
"Universal Music Group",
"The Hershey Company",
"Otis Worldwide",
"Digital Realty Trust",
"Quanta Services",
"SM Investments",
"CDW",
"Grupo Bimbo",
"Realty Income",
"ITC",
"ZTE",
"T&D Holdings",
"Essity",
"Fox",
"Alinma Bank",
"Joint Stock Commercial Bank for Foreign Trade of Vietnam",
"Mega Financial Holding",
"HF Sinclair",
"American Airlines Group",
"Carnival Corporation",
"MTR",
"Trip.com Group",
"Unipol Gruppo",
"BPER Banca",
"Hilton Worldwide Holdings",
"Chipotle Mexican Grill",
"Power Grid of India",
"Mapfre",
"Fresenius",
"CLP Holdings",
"JBS",
"Mitsubishi UFJ Lease",
"Geely Automobile Holdings",
"Kasikornbank",
"Tata Steel",
"Leonardo",
"Ameren",
"CenterPoint Energy",
"Cintas",
"Daiwa Securities",
"Rogers Communications",
"China Taiping Insurance",
"Microchip Technology",
"Motorola Solutions",
"TD SYNNEX",
"Builders FirstSource",
"Tohoku Electric Power",
"Corning",
"Credicorp",
"Eletrobrás",
"SK",
"Kuaishou Technology",
"Mitsui OSK Lines",
"Mazda Motor",
"Sandvik",
"Super Micro Computer",
"Tractor Supply",
"TDK",
"Flex",
"Woolworths",
"Southwest Airlines",
"Jiangxi Copper",
"HAL Trust",
"Philips",
"PPL",
"Workday",
"Tenaga Nasional",
"Public Storage",
"Mitsubishi Chemical",
"Mediobanca",
"Lululemon Athletica",
"Interactive Brokers Group",
"Longi Green Energy Technology",
"Kyocera",
"CP All",
"Absa Group",
"Jackson Financial",
"Sabanci Holding",
"Henderson Land",
"BDO Unibank",
"Chongqing Rural Bank",
"TCL",
"NASDAQ",
"Isuzu Motors",
"Phoenix Group Holdings",
"SDIC Power Holdings",
"Sumitomo Realty",
"Quinenco",
"Mizrahi Tefahot Bank",
"Evergreen Marine Corp. (Taiwan)",
"Greenland Holdings Group",
"Adidas",
"Banca MPS",
"Ford Otosan",
"Sichuan Road & Bridge",
"East Money Information",
"Aisin Seiki",
"Guotai Junan Securities",
"Commercial Bank For Investment & Development Of Vietnam",
"Dubai Islamic Bank",
"Arista Networks",
"IndusInd Bank",
"Westinghouse Air Brake Technologies",
"Monster Beverage",
"Jeronimo Martins",
"Dollar Tree",
"ON Semiconductor Corp.",
"Ovintiv",
"Hanwha",
"Naver",
"Suzano",
"Expedia Group",
"Telkom Indonesia",
"Tokyo Gas",
"China National Building",
"Fidelity National Information (FIS)",
"Saudi Arabian Mining",
"CMS Energy",
"Martin Marietta Materials",
"AES",
"Bank Of Chengdu",
"Indian Railway Finance",
"Legend Holding",
"Muyuan Foodstuff",
"DuPont De Nemours",
"Wipro",
"Delta Electronics",
"Mashreq Bank",
"Molson Coors Brewing",
"GAIL India",
"Moody's",
"Restaurant Brands International",
"Eversource Energy",
"Bank Pekao",
"Teva Pharmaceutical",
"Db Insurance",
"Legrand",
"Rakuten",
"Conagra Brands",
"Kellanova",
"Schindler Holding",
"Air France-KLM",
"TBEA",
"Bank Negara Indonesia",
"Welltower",
"Ericsson",
"Indian Bank",
"DSM-Firmenich",
"Waste Connections",
"Techtronic Industries",
"Raizen",
"Anta Sports Products",
"Kyushu Electric Power",
"Kone",
"Semiconductor Manufacturing International",
"Itaúsa",
"Halkbank",
"MOL Hungarian Oil",
"China Reinsurance Group",
"Formosa Petrochemical",
"Vedanta Limited",
"Ferrari",
"Shanghai International Port",
"Reliance Steel",
"Yuanta Financial Holding",
"NVR",
"Penske Automotive",
"St. James's Place",
"China Bohai Bank",
"China Three Gorges Renewables (Group)",
"Tongwei",
"SCB X Public Company",
"Vestas Wind Systems",
"KE Holdings",
"Dassault Systemes",
"DiDi Global",
"SK Innovation",
"CGI",
"American Water Works",
"Textron",
"Pembina Pipeline",
"Banque Saudi Fransi",
"Fosun International",
"Zimmer Biomet",
"Bangkok Bank",
"China National Chemical",
"Yum! Brands",
"Lithia Motors",
"Aena",
"Lonza Group",
"Synopsys",
"United Microelectronics",
"Uni-President",
"China Cinda Asset Management",
"Nongfu Spring",
"Scor",
"E.Sun Financial",
"Rockwell Automation",
"Santos",
"Kirin Holdings",
"Snam",
"Abu Dhabi Islamic Bank",
"KT",
"Sungrow Power Supply",
"Air Canada",
"CarMax",
"Dover",
"Zhejiang Zheneng Electric Power",
"Sunac China Holdings",
"Ferrovial",
"PBF Energy",
"Sanlam",
"Ulta Beauty",
"Yamaha Motor",
"All Nippon Airways",
"Viatris",
"Chunghwa Telecom",
"Live Nation Entertainment",
"Arab National Bank",
"Coles Group",
"XCMG Construction Machinery",
"GS Holdings",
"Franklin Resources",
"Ametek",
"Extra Space Storage",
"East West Bancorp",
"Flutter Entertainment",
"First Financial Holding",
"Electronic Arts",
"Experian",
"Beiersdorf",
"Nippon Paint",
"Avis Budget Group",
"Edwards Lifesciences",
"Agilent Technologies",
"Shenzhen Mindray Bio-Medical Electronics",
"Brookfield Reinsurance",
"Givaudan",
"Fastenal",
"Vienna Insurance Group",
"Brookfield Renewable",
"Qatar Islamic Bank",
"Globalfoundries",
"Jinko Solar",
"China Resources Pharmaceutical Group",
"HD HYUNDAI",
"International Flavors & Fragrances",
"Adani Power Limited",
"Eurobank Ergasias",
"Shaanxi Construction Engineering Group",
"Voya Financial",
"Sany Heavy Industry",
"Bank of India",
"Dick's Sporting Goods",
"Bank of Changsha",
"Luzhou Lao Jiao",
"Israel Discount Bank",
"China Development Financial",
"Adani Enterprises",
"T Rowe Price",
"Paychex",
"Shanghai Construction",
"Greentown China Holdings",
"Orsted",
"Shanxi Xinghuacun Fen Wine Factory",
"Paramount",
"Arca Continental",
"Wuchan Zhongda Group",
"Baxter International",
"Copart",
"Shanghai Pharmaceuticals",
"China CSSC Holdings",
"Darden Restaurants",
"LPL Financial Holdings",
"Jacobs Solutions",
"Guosen Securities",
"Vonovia",
"National Bank of Greece",
"GF Securities",
"Hua Nan Financial",
"WestRock",
"Coterra Energy",
"EXOR",
"SBI Holdings",
"Hormel Foods",
"Nedbank",
"M&G",
"Vulcan Materials",
"WPP",
"Cadence Design",
"AvalonBay Communities",
"Ternium",
"Antofagasta",
"China Merchants Securities",
"Spotify Technology",
"Grupo Carso",
"Osaka Gas",
"Interpublic Group",
"Kaspi.kz JSC",
"APA",
"WH Group",
"Agnico Eagle Mines",
"J Sainsbury",
"Julius Baer Group",
"Ingersoll Rand",
"WEG",
"Euronext",
"US Steel",
"Taiwan Cooperative Financial",
"Toll Brothers",
"Arrow Electronics",
"Western Digital",
"The Mosaic Company",
"Fortinet",
"ENN Natural Gas",
"Kajima",
"ENN Energy Holdings",
"Acciona",
"UPM-Kymmene",
"Guangzhou Automobile Group",
"DaVita",
"CNPC Capital",
"Constellation Software",
"Hoya",
"Banca Mediolanum",
"Amcor",
"Xylem",
"Marathon Oil",
"International Paper",
"El Puerto de Liverpool",
"EMCOR Group",
"Old Dominion Freight Line",
"Vibra Energia",
"ICON (Ireland)",
"US Foods",
"Hexagon",
"Top Frontier Investment Holdings",
"Weyerhaeuser",
"Atmos Energy",
"Terna",
"Assurant",
"Cathay Pacific Airways",
"Korea Gas",
"LKQ",
"XP",
"Asustek Computer",
"Telecom Italia",
"Industrivarden",
"Echostar",
"Krung Thai Bank",
"Vivendi",
"Cemex",
"NARI Technology Development",
"China Tourism Group Duty Free",
"Equity Residential",
"Prysmian",
"Garmin",
"MSCI",
"Japan Exchange Group",
"Owens Corning",
"Sun Pharma Industries",
"Amadeus IT Group",
"Wolters Kluwer",
"Bankinter",
"American Financial Group",
"SK Telecom",
"Investec",
"Chow Tai Fook Jewellery",
"Fortive",
"Sunshine Insurance Group",
"First Horizon",
"Rexel",
"Ball",
"Caesars Entertainment",
"Howmet Aerospace",
"SMC",
"ThyssenKrupp Group",
"Banco Comercial Portugues",
"Attijariwafa Bank",
"YPF",
"Stanley Black & Decker",
"SQM",
"Mitsubishi Motors",
"CJ Corporation",
"China Galaxy Securities",
"West Japan Railway",
"Chugoku Electric Power",
"Telenor",
"Universal Health Services",
"Metro",
"Partners Group Holding",
"Hydro One",
"China Southern Airlines",
"Bayan Resources",
"Vietin Bank",
"Olympus",
"StoneX Group",
"Yum China Holdings",
"Korean Air",
"Autodesk",
"Towngas",
"WESCO International",
"Westlake Chemical",
"Shenzhen Transsion Holding",
"Williams-Sonoma",
"J.B. Hunt Transport Services",
"Smurfit Kappa Group",
"Jyske Bank",
"Cellnex Telecom",
"Seazen Group",
"Forvia",
"InterGlobe Aviation",
"AutoNation",
"IDEXX Laboratories",
"Sodexo",
"Dassault Aviation",
"Grupo De Inversiones Suramericana",
"Oriental Land",
"Adani Ports & Special Economic Zone",
"Piraeus Financial Holdings",
"Performance Food Group",
"Webster Financial",
"iA Financial Corporation",
"Gerdau (Cosigua)",
"Brenntag",
"Hunan Valin Steel",
"Kobe Steel",
"Quest Diagnostics",
"Bunzl",
"GoDaddy",
"Compagnie de l'Odet",
"Pan Pacific International Holdings",
"AntarChile",
"Astellas Pharma",
"Huadian Power International",
"Swatch Group",
"Randstad N.V.",
"Origin Energy",
"Jiangsu Eastern Shenghong",
"ResMed",
"BCI-Banco Credito",
"Jiangsu Yanghe Brewery",
"Bank Of Guiyang",
"Norsk Hydro",
"Zhongyuan Bank",
"Vipshop Holdings",
"SinoPac Financial",
"Industries Qatar",
"Grupo Galicia",
"Csc Financial",
"Datang International Power",
"Pegatron",
"Evolution Gaming Group AB",
"Keppel",
"Olam Group",
"S-Oil",
"A2A",
"China International Capital",
"IDBI Bank",
"Dongguan Rural Commercial Bank",
"NiSource",
"Helvetia Holding",
"Yuexiu Property",
"Bajaj Auto",
"Grupo Aval",
"BAIC Motor",
"Alstom",
"Bâloise Group",
"Masco",
"Gartner",
"Keysight Technologies",
"Evergy",
"Adyen",
"Bank of Chongqing",
"Ajinomoto",
"Alpha Bank",
"Solventum",
"Brown & Brown",
"Sojitz",
"Halyk Bank",
"Fanuc",
"Shriram Transport Finance Co.",
"Hyundai Marine & Fire",
"Asahi Kasei",
"Jefferies Financial",
"Labcorp",
"Old Mutual",
"Xiamen International Trade Group",
"EQT",
"AGCO",
"NetApp",
"Voestalpine",
"Verisk Analytics",
"Corpay",
"Marfrig Global Foods",
"Eastman",
"Western Alliance Bancorp.",
"Bank Albilad",
"Leidos",
"PGE Polska Grupa Energetyczna",
"China Eastern Airlines",
"Tourmaline Oil",
"Kerry Group",
"Kingspan Group PLC",
"Zhongsheng Group Holdings",
"Dongfeng Motor Group",
"DexCom",
"Mettler-Toledo International",
"HBIS",
"AGNC Investment",
"ZTO Express (Cayman)",
"Shanghai Electric Group",
"DoorDash",
"Tianshan Material",
"Campbell Soup",
"Marvell Technology",
"Bank of Greece",
"Expeditors International",
"Hyundai Glovis",
"Storebrand",
"Brown-Forman",
"Foshan Haitian Flavouring and Food",
"Carvana",
"Wistron",
"Alexandria Real Estate Equities",
"Beijing Enterprises",
"Coca-Cola HBC",
"Rheinmetall",
"Gemdale",
"First Solar",
"Evonik Industries",
"Terumo",
"Robinhood Markets",
"BJ's Wholesale Club",
"Borouge",
"Bank of Suzhou",
"Solvay",
"Comerica",
"Wuxi Apptec",
"Far East Horizon",
"Xiamen Xiangyu",
"Ares Management",
"TUI",
"Epiroc",
"Metropolitan Bank & Trust",
"Shopify",
"Next",
"Church & Dwight",
"E-mart",
"Akzo Nobel",
"Rede D'Oro Luiz",
"Obayashi",
"STRABAG",
"Grupo Elektra",
"Valeo",
"Galaxy Entertainment",
"Qantas Airways",
"Bawag Group",
"ACWA Power",
"Aristocrat Leisure",
"Packaging Corp of America",
"Zions Bancorp",
"FinecoBank",
"China Mengniu Dairy",
"Broadridge Financial",
"Aramark",
"Lindt & Sprungli",
"Veralto",
"Qilu Bank",
"Jiangsu Hengrui Medicine",
"Hyundai Steel",
"Teledyne Technologies",
"Tokyo Century",
"BBMG",
"China Jinmao",
"Coloplast",
"Shin Kong Financial",
"Roivant Sciences",
"Carlsberg",
"McCormick",
"China Steel",
"Shimao Property Holdings",
"Banque Cantonale Vaudoise",
"Ag Anadolu Grubu Holding Anonim Sirketi",
"Asian Paints",
"Wens Foodstuff Group",
"Credito Emiliano",
"China Merchants Expressway Network & Technology Holdings",
"Annaly Capital Management",
"Latam Airlines",
"Dollarama",
"Hong Leong Financial",
"Chongqing Zhifei Biological Products",
"China Nuclear Engineering Corporation",
"Murphy USA",
"Bank of Tianjin",
"HPB",
"Trina Solar",
"Hotai Motor",
"Korea Shipbuilding & Offshore Engineering",
"Aeroports de Paris",
"China Resources Gas Group",
"Motor Oil",
"Lumen Technologies",
"CF Industries Holdings",
"RHB Bank",
"CJ Cheiljedang",
"DISCO Corp.",
"Avery Dennison",
"China Shipbuilding Industry",
"BNK Financial Group",
"Casey's General Stores",
"Huntington Ingalls Industries",
"Sandoz Group",
"Guangdong Haid Group",
"Lamb Weston Holdings",
"LG Display",
"New World Development",
"Zhuhai Huafa Properties",
"JDE Peet's",
"Rithm Capital",
"Unibail-Rodamco-Westfield",
"Shenwan Hongyuan Group",
"Invitation Homes",
"Sumitomo Chemical",
"Toray Industries",
"Alliant Energy",
"Transurban Group",
"China Communications Services",
"Sinotruk Hong Kong",
"Commercial Bank of Qatar",
"Hubei Biocause Pharmaceutical",
"China International Marine",
"Secom",
"ASM International",
"Lundbergs",
"Avnet",
"Kao",
"Concordia Financial Group",
"Globe Life",
"Siam Cement",
"Deckers Outdoor",
"Suntory Beverage & Food",
"WSP",
"Wharf Real Estate Investment",
"BIM Birlesik Magazalar",
"Lear",
"SSAB",
"Korea Investment Holdings",
"Hyundai Engineering",
"Charoen Pokphand Group",
"Goodyear",
"Military Commercial Joint Stock Bank",
"Wintrust Financial",
"Jones Lang LaSalle",
"Carlisle Cos",
"Snap-on",
"Fukuoka Financial Group",
"CBOE Global Markets",
"Genmab",
"Booz Allen Hamilton Holding",
"Advanced Info Service",
"BorgWarner",
"New York Community Bancorp",
"Old Republic International",
"Hubbell",
"Lotte Chemical",
"Moderna",
"Colruyt",
"China Longyuan Power",
"Hyatt Hotels",
"Bank of Qingdao",
"SGS",
"Cleveland-Cliffs",
"Bath & Body Works",
"Empire",
"Ultrapar Participacoes",
"Vietnam Technological & Commercial Joint Stock Bank",
"Guangzhou Rural Commercial Bank",
"LG",
"Check Point Software",
"CIFI Holdings Group",
"Bank of Guizhou",
"VeriSign",
"Vertiv Holdings",
"Ningxia Baofeng Energy Group",
"Stora Enso",
"KPN",
"Shenzhen Inovance Technology",
"Chiba Bank",
"China Development Bank Financial Leasing",
"First Pacific",
"Prada",
"Albemarle",
"Cosmo Energy Holdings",
"Equifax",
"AppLovin",
"Knorr-Bremse",
"Grupo Bolivar",
"Brighthouse Financial",
"Bank of East Asia",
"Schaeffler",
"Japan Airlines",
"AECOM",
"Shionogi",
"Unicharm",
"Taishin Financial Holdings",
"Bandai Namco Holdings",
"Geberit",
"Veeva Systems",
"Hangzhou Binjiang Real Estate Group Co., Ltd.",
"CrowdStrike",
"Sumitomo Forestry Co.,",
"Anhui Gujing Distillery",
"News Corp",
"Banca Popolare di Sondrio",
"SS&C Technologies",
"Ventas",
"Wheaton Precious Metals",
"CPFL Energia",
"MTN Group",
"Skyworks Solutions",
"Sime Darby",
"Group 1 Automotive",
"Dr. Sulaiman Al-Habib Medical Services Group",
"Nan Ya Plastics",
"PTT Global Chemical",
"Sasol",
"Genworth Financial",
"Macy's",
"Falabella",
"Fuyao Glass Industry Group",
"U-Haul Holding",
"Tata Power Company",
"West Pharmaceutical Services",
"World Fuel Services",
"Goodman Group",
"United Therapeutics",
"Banca Transilvania",
"Qinghai Salt Lake Industry",
"Shengjing Bank",
"Cadence Bank",
"NAURA Technology GroupLtd",
"Wynn Resorts",
"Brambles",
"Chesapeake Energy",
"Iveco Group",
"Mebuki Financial Group",
"Royalty Pharma",
"Sonova Holding",
"Chailease Holding",
"Shanghai Commercial & Savings Bank",
"Bank OZK",
"China Huarong Asset Management",
"Popular",
"Fair Isaac",
"Chang Hwa Bank",
"Zoom Video Communications",
"InterContinental Hotels",
"HMM",
"Migdal Insurance",
"Shizuoka Financial Group",
"Titan (India)",
"Waters",
"Moncler SpA",
"Shenzhen Overseas",
"Old National Bank",
"Rajesh Exports",
"Snowflake",
"TMBThanachart Bank",
"Whirlpool",
"Watsco",
"Hellenic Petroleum",
"Cullen/Frost Bankers",
"Harbin Bank",
"Alfa Laval",
"FCC",
"Doosan",
"Emera",
"China Resources Beer (Holdings)",
"Commercial Bank Dubai",
"JM Smucker",
"RPM International",
"Pinnacle Financial Partners",
"AviChina Industry & Technology",
"Virgin Money UK",
"C.H. Robinson",
"Hokuhoku Financial Group",
"NOV",
"Unicaja Banco",
"Chandra Asri Petrochemical",
"Stifel Financial",
"Haitong Securities",
"Gen Digital",
"Covestro",
"Metro Group",
"Inner Mongolia Baotou Steel",
"Palantir Technologies",
"Asbury Automotive Group",
"Fortum",
"Mirae Asset Financial Group",
"Ayala Corp",
"Atlassian",
"Jio Financial Services",
"PT Amman Mineral Internasional",
"SLM",
"Trade Desk",
"Hachijuni Bank",
"New Hope Liuhe",
"SBA Communications",
"Electric Power Development",
"Autoliv",
"United Natural Foods",
"Midea Real Estate Holding",
"Anhui Construction Engineering Group",
"Compal Electronics",
"Avenue Supermarts",
"Beijing Shougang",
"BAC Holding International",
"Synovus",
"DCC",
"Link REIT",
"Japan Securities",
"Iron Mountain",
"SKF Group",
"D'Ieteren",
"Thai Beverage",
"Zheshang Development Group",
"Altice USA",
"Kyushu Financial Group",
"Nishi-nippon Financial Holdings",
"Rakuten Bank",
"Starwood Property Trust",
"Tapestry",
"UCB",
"Monolithic Power Systems",
"Bank of Zhengzhou",
"Sinotrans Ltd.",
"Insurance Australia Group",
"North Pacific Bank",
"Huaibei Mining Holdings",
"Lennox International",
"Airports of Thailand",
"Cencosud",
"Valley National Bancorp",
"Formosa Chemicals",
"Hirogin Holdings",
"Gold Fields",
"Zhejiang Expressway Co. Ltd.",
"Columbia Bank",
"Datadog",
"Companhia Energetica de Minas Gerais",
"Liberty Global",
"W. P. Carey",
"Yamaguchi Financial",
"Jiangsu Zhongnan Construction Group",
"Thai Oil",
"B3",
"Gap",
"Novonesis A/S",
"Power Assets Holdings",
"Sumitomo Metal Mining",
"Commercial International Bank",
"ARC Resources",
"Asia Commercial Bank",
"Shenzhou International Group Holdings",
"AGC",
"Adecco Group",
"Avolta",
"Graphic Packaging",
"BayWa",
"Daou Data",
"Brookfield Business",
"Dai Nippon Printing",
"Skechers USA",
"EQT AB",
"Jiangxi Bank",
"Jiangsu Changshu Rural Commercial Bank",
"Heico",
"Ansys",
"Kyoto Financial Group",
"Skanska",
"Arab Bank",
"Segro",
"Incyte",
"Crown Holdings",
"Seres Group",
"Ampol",
"Medipal Holdings",
"Wuestenrot & Wuerttembergische",
"Daishi Hokuetsu Financial Group",
"CoStar Group",
"Jindal Steel & Power",
"Host Hotels & Resorts",
"Ceconomy",
"Eurazeo",
"Hengyi Petrochemical",
"LIC Housing Finance",
"Adani Green Energy",
"DGB Financial Group",
"Lasertec",
"China Grand Automotive Services",
"Gunma Bank",
"Bajaj Holdings & Investment",
"Celltrion",
"Chugin Financial Group,Inc.",
"Bank of Jiujiang",
"KION Group",
"Rite Aid",
"Orpea",
"Focus Media Information Technology",
"CTP",
"Umicore",
"Warner Music Group",
"SBI Sumishin Net Bank",
"Toppan Printing",
"Everbright Securities",
"Parkland",
"Shanghai Tunnel Engineering Co. Ltd.",
"Taiwan Business Bank",
"Telia",
"77 Bank",
"Kawasaki Kisen Kaisha",
"IDEX",
"Indorama Ventures",
"Kingfisher",
"Braskem",
"Lotte Shopping",
"Gaming And Leisure Properties",
"Quilter",
"Bendigo & Adelaide Bank",
"Daou Technology",
"BOK Financial",
"Marks & Spencer",
"Berry Global Group",
"WPG Holdings",
"Shandong Gold Mining",
"China Merchants Port Holdings",
"PT Adaro Energy Indonesia",
"Advantest",
"Ooredoo Q.P.S.C",
"Pandora",
"Bank of Queensland",
"Jinke Property Group",
"Air Lease",
"Latour Ab Investment",
"Haidilao International Holding",
"Oshkosh",
"Luzerner Kantonalbank",
"Akamai Technologies",
"Qingdao Rural Commercial Bank",
"South State",
"HubSpot",
"Domino's Pizza",
"Nitto Denko",
"Carlyle Group",
"WT Microelectronics",
"Zenith Bank",
"CP Axtra",
"General Insurance Corporation Of India",
"EMS-Chemie Holding",
"F.N.B.",
"Nitori Holdings",
"Bank of Lanzhou",
"LG Innotek Co.,",
"Drax Group plc",
"AVIC Capital",
"Jointown Pharmaceutical Group",
"Yes Bank",
"Yunnan Copper Co. Ltd.",
"Basler Kantonalbank",
"Axis Capital Holdings",
"Bausch Health Companies",
"Nova Ljubljanska Banka",
"Zhongliang Holdings",
"Pentair",
"CapitaMall Trust",
"Samsung SDS",
"FIBI Holdings",
"Mondi",
"RiseSun Real Estate Development",
"Iyogin Holdings,Inc.",
"Bank of Xi'an",
"JB Financial Group",
"Mid-america Apartment Communities",
"Burlington Stores",
"Alfresa Holdings",
"Pinterest",
"Rollins",
"Goneo GroupClass A",
"Südzucker",
"Adris grupa d.d. Pref.",
"Mobileye Global",
"E-L Financial",
"Logitech International",
"Navient",
"Grupo Comercial Chedraui SAB de CV Class B",
"NH Investment & Securities",
"Liberty Media Corporation Series A Liberty Formula One",
"Hertz Global Holdings",
"MicroStrategy",
"Fibra Uno",
"Novatek Microelectronics Corp.",
"Redeia Corporacion",
"Samvardhana Motherson International",
"Nomura Research Institute",
"Align Technology",
"Bureau Veritas",
"Essex Property Trust",
"JA Solar Technology",
"Bluescope Steel",
"Henry Schein",
"Deutsche Pfandbriefbank",
"Hera",
"Harel Insurance Investments & Financial Services",
"KakaoBank",
"Pinnacle West",
"Founder Securities",
"Tongling Nonferrous Metals",
"Weihai City Commercial Bank",
"Bharat Electronics Limited",
"Ricoh",
"Xiamen Bank",
"MongoDB",
"Phoenix Holdings",
"Bank Of Gansu",
"Cosan",
"Zscaler",
"Bank Muscat",
"Manpower",
"Diebold Nixdorf",
"Clorox",
"Metalurgica Gerdau",
"Snap",
"TopBuild",
"Dentsu",
"Orient Securities",
"CSPC Pharmaceutical Group",
"LS Corp",
"Central Bank of India",
"Yara International",
"Bank of Maharashtra",
"Shimizu",
"Healthpeak Properties",
"Kawasaki Heavy Industries",
"Tradeweb Markets",
"Hyakugo Bank",
"Indus Towers",
"Kesko",
"China Power International Development",
"Kakao",
"Trelleborg Group",
"Steel Authority of India",
"CAPITEC",
"First Quantum Minerals",
"Almarai",
"Aurubis",
"Banque Centrale Populaire",
"Nexi S.p.A.",
"Enstar Group",
"Shiga Bank",
"Tryg",
"Erie Indemnity",
"Ramsay Health Care",
"Var Energi ASA",
"Viva Energy Group",
"United Bank for Africa",
"Zall Smart Commerce Group",
"Federal Bank",
"Cloudflare",
"MBH Bank Plc.",
"PVH",
"Aareal Bank",
"Kohl's",
"Samsung Securities",
"Momentum Metropolitan Holdings",
"Jinshang Bank",
"Take-Two Interactive Software",
"DLF",
"Johnson Matthey",
"Aozora Bank",
"Guangzhou Baiyunshan Pharmaceutical Holdings",
"Teradyne",
"Mercuries & Associates",
"Rentokil Initial",
"Juroku  Financial Group",
"Franco-Nevada",
"Daito Trust Construction",
"nVent Electric",
"Banco Davivienda",
"Digital China Group",
"Informa plc",
"Jiangxi Zhengbang Technology",
"Seagate Technology",
"Dr. Reddy's Laboratories",
"Avantor",
"St. Galler Kantonalbank",
"Essential Utilities",
"Hanwa",
"Yunnan Baiyao Group",
"Bank of Cyprus Holdings",
"San-In Godo Bank",
"China Fortune Land Development",
"Teleperformance",
"Inventec",
"OneMain Holdings",
"Organon",
"FactSet Research Systems",
"Varun Beverages",
"Steris",
"NIO",
"Open House",
"TFI International",
"BEKB-BCBE",
"Sabesp",
"Scentre Group",
"IHH Healthcare",
"Tokyo Kiraboshi Financial Group",
"Shanxi Xishan Coal & Electricity Power Co. Ltd.",
"Wharf (Holdings)",
"Cameco",
"CVR Energy",
"Guangzhou R&F",
"Suzuken",
"Logan Property Holdings",
"Schibsted ASA",
"Taylor Morrison Home",
"Barry Callebaut",
"NIPPON EXPRESS HOLDINGS",
"FMC",
"Ralph Lauren",
"ALFA",
"Commercial Metals",
"Taisei",
"Hologic",
"Signet Jewelers",
"Inner Mongolia Yitai Coal",
"Masraf Al Rayan",
"Saputo",
"Samsara",
"China Gas Holdings",
"Delek US Holdings",
"EFG International",
"Zhangzhou Pientzehuang Pharmaceutical",
"Sumec Corporation",
"Ipsen",
"Manila Electric",
"Public Power",
"Cholamandalam Investment and Finance",
"Yunnan Yuntianhua",
"PTC",
"UMB Financial",
"arGEN-X",
"Sharp",
"Kyndryl Holdings",
"Lotte",
"Aichi Financial Group",
"A.O. Smith",
"NMDC",
"AltaGas",
"Cogent Communications",
"Axon Enterprise",
"Nanto Bank",
"Aier Eye Hospital Group",
"XPO",
"Toho Bank",
"Wisetech Global",
"Celsius Holdings",
"Clal Insurance Enterprises",
"Buzzi Unicem",
"Canadian Tire Corporation",
"Ingredion",
"Ogaki Kyoritsu Bank",
"Euronav",
"Saudi Investment Bank",
"Nordson",
"H World Group",
"Straumann Holding",
"Ningbo Jintian Copper (Group)",
"Abb India",
"China Merchants Energy Shipping",
"Fluor",
"AmBank Group",
"Equatorial Energia",
"Uniqa",
"Delivery Hero",
"Kimco Realty",
"Puig Brands",
"Zhejiang Construction Investment Group",
"Keiyo Bank",
"Sun Communities",
"Roblox",
"China Merchants Port Group",
"DraftKings",
"Guangdong Construction Engineering Group",
"Angang Steel",
"Sichuan Chuantou Energy",
"Vietnam Prosperity Joint-sock Commercial Bank",
"Adient",
"CapitaLand Investment",
"Shanxi Lu'an Environmental",
    
]

# Это только пример. Полный список из 2000+ брендов нужно добавить сюда 